config/routes.rb
Englishhome2::Application.routes.draw do

  root :to => "shop#index", :as => "shop"

  resources :products do
    collection do
      get 'search'
    end
  end

  resources :categories do
  end

  resources :collections do
    collection do
      get 'classic'
      get 'contemporary'
    end
  end

  match 'info/contact_us' => 'shop#contact_us'
  match 'info/about_us' => 'shop#about_us'
  match 'info/shipping' => 'shop#shipping'
  match 'info/trade' => 'shop#trade'

    namespace :admin do

      root :to => "products#index", :as => "root"

      resources :products do
        member do
          post 'upload_photo'
        end
      end
      resources :attributes
      resources :gallery_images do
        member do
          post 'upload'
        end
      end
      resources :designs do
        member do
          post 'moodshot'
          post 'list_photo'
        end
      end
      resources :users
      resources :imports do
        collection do
          post 'import_price_list'
          post 'import_image'
        end
      end

      resources :vendors
      resources :site_texts

      resources :image_imports
      resources :price_list_imports
      resources :menu_images do
        member do
          post 'upload_photo'
        end
      end

      resource :user_session
      match 'login' => "user_sessions#new",      :as => :login
      match 'logout' => "user_sessions#destroy", :as => :logout
    end

  get "/500", :to => "errors#server_error"
  get "/404", :to => "errors#not_found"

end

app/controllers/collections_controller.rb
class CollectionsController < ShopController

  def index
    @images = GalleryImage.to_be_shown.all(:order => "position ASC")
  end

  def show
    if params[:id] == "accents"
      case params[:style]
      when 'contemporary'
        style_conditions = " AND products.collection_type = 0"
        @title = "Contemporary Accent cushion covers"
      when 'classic'
        style_conditions = " AND products.collection_type = 1"
        @title = "Classic Accent cushion covers"
      else
        @title = "Accent cushion covers"
      end

      joins_condition = "INNER JOIN products ON
        products.product_code_id = attributes.id AND
        products.accent_id IS NOT NULL AND
        products.photo_file_name IS NOT NULL AND
        products.price IS NOT NULL"
      joins_condition += style_conditions if style_conditions


      @product_types = ProductCode.all(
        :select => "attributes.*, count(products.id) as product_count",
        :joins => joins_condition,
        :group => "attributes.id",
        :order => "product_code_position ASC")
    else
      @design = Design.find(params[:id])
      @title = "#{@design.name} collection"
      @product_types = ProductCode.all(
        :select => "attributes.*, count(products.id) as product_count",
        :joins => "INNER JOIN products ON
          products.product_code_id = attributes.id AND
          products.design_id = #{@design.id} AND
          products.photo_file_name IS NOT NULL AND
          products.price IS NOT NULL",
        :group => "attributes.id",
        :order => "product_code_position ASC")
    end




    @products = []
    @product_types.each do |product_type|
      if @design
        conditions = ["design_id = ? AND
                      photo_file_name IS NOT NULL AND
                      products.price IS NOT NULL", @design.to_param]
      else
        conditions = ["accent_id IN (?) AND
                      photo_file_name IS NOT NULL AND
                      products.price IS NOT NULL",
                      Product.unscoped.pluck(:accent_id).uniq.compact]
        conditions[0] += style_conditions if style_conditions
      end
      @products.concat product_type.products.find(:all, :conditions => conditions)
    end

    @product_rows = [[]]
    @products.compact.uniq.each do |product|
      if @product_rows.last.size==3
        @product_rows << []
      end
      @product_rows.last << product
    end
    if @product_rows.count == 1 && @product_rows.first.count != 3
      @product_rows.first << "empty" if @product_rows.first.count == 1
      @product_rows.first << "empty" if @product_rows.first.count == 2
    end
  end

  def contemporary
    @collections = Design.contemporary.
      where("products_count > 0").includes(:products).
      where("products.accent_id IS NULL AND
        products.photo_file_name IS NOT NULL AND
        products.price IS NOT NULL")
    @collection_rows = [[]]
    @title = "Collections"
    for collection in @collections
      if collection.products.count >0
        if @collection_rows.last.size==3
          @collection_rows << []
        end

        @collection_rows.last << collection
      end
    end
  end

  def classic
    @collections = Design.classic.
      where("products_count > 0").includes(:products).
      where("products.accent_id IS NULL AND
      products.photo_file_name IS NOT NULL AND
      products.price IS NOT NULL")
    @collection_rows = [[]]
    @title = "Collections"
    for collection in @collections
      if collection.products.count >0
        if @collection_rows.last.size==3
          @collection_rows << []
        end

        @collection_rows.last << collection
      end
    end
  end
end

app/views/collections/classic.html.haml
%h1
  Classic collections
#products

  %table.all-items{:cellspacing => "0", :cellpadding => "0", :style => "width: 960px"}

    - @collection_rows.each do |collection_row|
      %tr
        -collection_row.each do |collection|
          %td
            .holder
              - if collection.products.first.design.list_photo.exists?
                - img = collection.products.first.design.list_photo.url(:preview)
                - css_class = "list-photo"
              - elsif collection.products.first.design.photo.exists?
                - img = collection.products.first.design.photo.url(:preview)
                - css_class = "design"
              - else
                - img = collection.products.first.photo.url(:preview)
                - css_class = "product"
              .image-holder= link_to image_tag(img, :alt => collection.name), collection_path(collection), :class => "img #{css_class}"
              .name
                = link_to collection.name, collection_path(collection)

  .clear

app/views/collections/contemporary.html.haml
%h1
  Contemporary collections
#products

  %table.all-items{:cellspacing => "0", :cellpadding => "0", :style => "width: 960px"}

    - @collection_rows.each do |collection_row|
      %tr
        -collection_row.each do |collection|
          %td
            .holder
              - if collection.products.first.design.list_photo.exists?
                - img = collection.products.first.design.list_photo.url(:preview)
                - css_class = "list-photo"
              - elsif collection.products.first.design.photo.exists?
                - img = collection.products.first.design.photo.url(:preview)
                - css_class = "design"
              - else
                - img = collection.products.first.photo.url(:preview)
                - css_class = "product"
              = link_to image_tag(img, :alt => collection.name), collection_path(collection), :class => "img #{css_class}"
              .name
                = link_to collection.name, collection_path(collection)

  .clear

app/views/collections/index.haml
- if @images.any?
  #gallery
    .slides
      - first = true
      - @images.each do |image|
        .slide{:style => ("display: none" if !first), :id => dom_id(image)}
          %img{:href => image.image.url(:zoom), :src => (image.image.url(:zoom) if first), :width => "960px"}
          - first = false
          - collections = [image.collection1, image.collection2, image.collection3].compact
          .caption
            - if collections.any?
              Featured Collections:
              = collections.map {|c| link_to c.name.strip, collection_path(c)}.join(", ").html_safe
            - else
              &nbsp;




    .thumbs
      %ol{:style => "width:#{@images.count*144}px"}
        - first = true
        - @images.each do |image|
          %li.thumb{:slide => dom_id(image), :class => ("current" if first)}
            - first = false
            %img{:src => image.image.url(:thumb)}
            .border
      .left
        <
      .right
        >
  .clear
- else
  / #home_image{:style => "width: 800px; margin: 0 auto;"}
  /   = image_tag "homepage2.jpg", :height => 532, :alt => ""

app/views/collections/show.haml
#products{:class => ('view-all-collection' if @design && @design.photo.exists? )}
  - if @design && @design.photo.exists?
    .moodshot
      = image_tag(@design.photo.url(:moodshot))
      %h1.title= @title
      / .text
      /   Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet, consectetur, adipisci[ng] velit, sed quia non numquam [do] eius modi tempora inci[di]dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur?
  - else
    %h1= @title


  %table.products{:cellspacing => "0", :cellpadding => "0", :style => "width: 960px; clear: both; margin-bottom: 20px"}
    - @product_rows.each do |product_row|
      %tr
        -product_row.each do |product|
          %td
            - next if product == "empty"
            %div
              = link_to image_tag(product.photo.url(:preview), :alt => product.short_name), product_path(product), :class => "img"
              .name
                = link_to product.short_name, product_path(product)
              .product-type
                = product.product_code.name