config/routes.rb
Englishhome2::Application.routes.draw do

  root :to => "shop#index", :as => "shop"

  resources :products do
    collection do
      get 'search'
    end
  end

  resources :categories do
  end

  resources :collections do
    collection do
      get 'classic'
      get 'contemporary'
    end
  end

  match 'info/contact_us' => 'shop#contact_us'
  match 'info/about_us' => 'shop#about_us'
  match 'info/shipping' => 'shop#shipping'
  match 'info/trade' => 'shop#trade'

    namespace :admin do

      root :to => "products#index", :as => "root"

      resources :products do
        member do
          post 'upload_photo'
        end
      end
      resources :attributes
      resources :gallery_images do
        member do
          post 'upload'
        end
      end
      resources :designs do
        member do
          post 'moodshot'
          post 'list_photo'
        end
      end
      resources :users
      resources :imports do
        collection do
          post 'import_price_list'
          post 'import_image'
        end
      end

      resources :vendors
      resources :site_texts

      resources :image_imports
      resources :price_list_imports
      resources :menu_images do
        member do
          post 'upload_photo'
        end
      end

      resource :user_session
      match 'login' => "user_sessions#new",      :as => :login
      match 'logout' => "user_sessions#destroy", :as => :logout
    end

  get "/500", :to => "errors#server_error"
  get "/404", :to => "errors#not_found"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :deleted_at
end

app/controllers/categories_controller.rb
class CategoriesController < ShopController

  def index
    @title = "Categories"
    @categories = ProductCode.active
    @category_rows = [[]]

    for category in @categories

        if @category_rows.last.size==3
          @category_rows << []
        end

        @category_rows.last << category

    end
  end

  def show

    @category = ProductCode.find(params[:id])
    @title = @category.name.pluralize

    params.reject! {|p,k| k.blank?}

    @conditions = {:product_code_id => @category.id}.merge(params.reject {|p,k| !Product::FACET_ATTRIBUTES.include?(p.to_sym)})
    @conditions.merge!(:collection_type => (params['collection'].titlecase == "Classic")) if params['collection']
    @conditions.merge!(:photo_file_size => 1..1000000000) # Max Filesize?
    @conditions.merge!(:price => 1.0..999999999999.9) # Max Price?
    Rails.logger.info("\n\n----> Conditions: #{@conditions}")

    if params[:view_all]
      @products = Product.search :with => @conditions, :page => params[:page], :per_page => 500, :order => "name ASC"
    else
      @products = Product.search :with => @conditions, :page => params[:page], :order => "name ASC", :per_page => 12
    end
    @facets = Product.process_facets(Product.facets :with => @conditions, :per_page => 200)

    @product_rows = [[]]

    for product in @products
      if @product_rows.last.size == 3
        @product_rows << []
      end

      @product_rows.last << product
    end

    if @product_rows.count == 1 && @product_rows.first.count != 3
      @product_rows.first << "empty" if @product_rows.first.count == 1
      @product_rows.first << "empty" if @product_rows.first.count == 2
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  FILTER_MAP = {:design_id => "Collection",
                :base_fabric_id => "Fabric",
                :base_colour_id => "Colour"}
  def filter_name(key)
    "Filter by #{FILTER_MAP[key] || key.to_s.titleize}"
  end
end

app/views/categories/index.haml
%h1
  Categories
#products

  %table.products{:cellspacing => "1", :cellpadding => "0", :style => "width: 960px"}

    - @category_rows.each do |category_row|
      %tr
        -category_row.each do |category|
          %td{:width => "#{100/3}%"}
            %div
              = link_to image_tag(category.products.first.photo.url(:thumb)), category_path(category), :class => "img", :alt => category.name.pluralize
              .name
                = link_to category.name.pluralize, category_path(category)

  .clear

app/views/categories/show.haml
#products
  %h1
    = @category.name.pluralize.humanize

  %table.filters{:style => "float: left"}
    %tr
      - @facets.each do |k,options|
        - if (options.count==1) and params[k]
          %td
            #{k.to_s.titleize} is <em>#{options.first[0].name}</em>
            = link_to "(Remove)", url_for(:overwrite_params => {"#{k.to_s}" => nil}, :collection => params['collection'])
      - @facets.each do |k,options|
        - if options.count>1
          %td.filter
            = form_tag "", :method => :get do
              = hidden_field_tag :collection, params['collection']
              - params.each do |param, value|
                = hidden_field_tag param, value if Product::FACET_ATTRIBUTES.include?(param.to_sym)

              = select_tag k, options_for_select(options.map {|option,count| ["#{option.name} (#{count})", option.to_param]}.sort {|a,b| a[0] <=> b[0]}.insert(0, [filter_name(k), nil])), {:name => "#{k.to_s}"}
              = submit_tag "Filter", :name => nil

  - if params[:view_all].present?
    .pagination
      = link_to  "View 12 per page", url_for(:overwrite_params => {"view_all" => nil}, :collection => params['collection'])
  - else
    =will_paginate @products, :inner_window => 1, :outer_window => 0, :renderer => PaginationRenderer
    .pagination
      = link_to  "View all", url_for(:view_all => true, :collection => params['collection'])
  %table.products{:cellspacing => "0", :cellpadding => "0", :style => "width: 960px; clear: both"}

    - @product_rows.each do |product_row|
      %tr
        -product_row.each do |product|
          %td
            - next if product == "empty"
            .image
              = link_to image_tag(product.photo.url(:preview), :alt => product.short_name), product_path(product), :class => "img"
            .name
              = link_to product.short_name, product_path(product)
  .bottom
    - if params[:view_all].present?
      .pagination
        = link_to  "View 12 per page", url_for(:overwrite_params => {"view_all" => nil}, :collection => params['collection'])
    - else
      =will_paginate @products, :inner_window => 3, :renderer => PaginationRenderer
      .pagination
        = link_to  "View all", url_for(:view_all => true, :collection => params['collection'])
  .clear